# Generated by Django 5.2 on 2025-11-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accident_images/')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('alerted', 'Alerted'), ('enroute', 'En Route'), ('resolved', 'Resolved')], default='reported', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned_hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('live_distance_km', models.FloatField(blank=True, null=True)),
                ('eta_min', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
